apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: spring-sample-deployment
  labels:
    app: sample-spring-kubernetes-azure
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-spring-kubernetes-azure
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: sample-spring-kubernetes-azure
    spec:
      containers:
      - name: sample-spring-kubernetes-azure
        image: ${docker.image.prefix}/${project.artifactId}:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 0.1
            memory: "1Gi"
      imagePullSecrets:
      - name: spring-sample-secrets