apiVersion: v1
kind: Service
metadata:
  name: spring-sample-service
  labels:
    expose: "true"
spec:
  selector:
    app: sample-spring-kubernetes-azure
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
